DROP PROCEDURE IF EXISTS SP_PRODUCT_CATEGORY_UPDATE;
DELIMITER $
CREATE PROCEDURE SP_PRODUCT_CATEGORY_UPDATE(
    IN _id INT,
    IN _name VARCHAR(64),
    IN _photo LONGTEXT)
BEGIN
    UPDATE ProductCategory SET
        Name = _name,
        Photo = _photo
    WHERE Id = _id;
END $
DELIMITER ;
