DROP TABLE IF EXISTS ProductCategory;

CREATE TABLE ProductCategory (
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(64) NOT NULL,
    Photo LONGTEXT NOT NULL,
    Active BOOLEAN NOT NULL
);