DROP TABLE IF EXISTS UserToken;

CREATE TABLE UserToken (
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Id_User INT NOT NULL,
    Token CHAR(32) NOT NULL,
    LastDate DATETIME NOT NULL,

    FOREIGN KEY (Id_User) REFERENCES User(Id)
);